### ISSUE TITLE
`[1 templating/parsing errors found]` was inserted after format

### ISSUE THREAD

**Issue by Aria461863631** [yaegassy/coc-sqlfluff#13] opened 2022-09-25 08:32 UTC
with latest coc

**Comment by yaegassy** [comment] 2022-09-25 12:06
I do not know how to reproduce it. Please post a code snippet of SQL that I can reproduce.

**Comment by yaegassy** [comment] 2023-03-27 03:38
I am closing this issue as I cannot reproduce this issue in my environment.

**Closed as completed by yaegassy** 2023-03-27 03:38 UTC
